Excersice 6

In [1]:
import numpy as np
x = [[1],[1],[1]]
xt = np.transpose(x)
print(np.matmul(x,xt))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


Excersice 7

In [2]:
import numpy as np
i = [[1,0,0],[0,1,0],[0,0,1]]
o = [[1],[1],[1]]
ot = np.transpose(o)
x= [[2],[1],[2]]
s1 = np.matmul(o,ot)
s2 = np.dot(1/3,s1)
h = np.subtract(i,s2)
hx = np.matmul(h,x)
h2 = np.matmul(h,h)
h3 = np.matmul(h2,h)
h2x = np.matmul(h3,x)
hx, h2x

(array([[ 0.33333333],
        [-0.66666667],
        [ 0.33333333]]),
 array([[ 0.33333333],
        [-0.66666667],
        [ 0.33333333]]))

In [50]:
import numpy as np

u = np.dot(1/np.sqrt(5),np.transpose([1,2]))

x1 = np.transpose([1,2])
ux1 = np.matmul(u,x1)
p1 = np.dot(ux1,u)
print(p1)


x2 = np.transpose([3,4])
ux2 = np.matmul(u,x2)
p2 = np.dot(np.matmul(u,x2),u)
print(p2)


x3 = np.transpose([-1,0])
ux3 = np.matmul(u,x3)
p3 = np.dot(np.matmul(u,x3),u)
print(p3)

# emperical variance
emp_var = np.var([ux1,ux2,ux3])
# print(emp_var)

# compute s
X = [np.transpose(x1),np.transpose(x2),np.transpose(x3)]
emp_cov = np.cov(X)
# print(emp_cov)
s = np.matmul(np.dot(1/3,np.transpose(X)),np.matmul(h,X))
np.matmul(np.transpose(u), np.matmul(s,u))
# s


[1. 2.]
[2.2 4.4]
[-0.2 -0.4]


4.8

In [10]:
u = [1,0]
# np.matmul(np.transpose(u),u)
np.var(u), np.var(np.matmul(u,u))

(0.25, 0.0)

In [16]:
i = [[1,0],[0,1]]
v = [[2,0],[0,2]]
vi = np.linalg.inv(v)
# np.dot(2,v)
np.matmul(i,v)

array([[2, 0],
       [0, 2]])

Excersice 9

In [26]:
def IdentityMatrix(n):
    i_mat = []
    for r in range(n):
        row = []
        for c in range(n):
            if r==c:
                row.append(1)
            else:
                row.append(0)
        i_mat.append(row)
    return i_mat



In [56]:
n = 2
i = IdentityMatrix(n)
x = np.ones(n)
xt = np.transpose(x)
xxt = np.matmul(x,xt)
H = np.subtract(i,1)
np.matmul(H,H), np.matmul(np.linalg.inv(H),H)

(array([[1, 0],
        [0, 1]]),
 array([[1., 0.],
        [0., 1.]]))

In [ ]:
x1 = [0,1]
x2 = [0,-1]
S  = (1/2)* 

In [66]:
# Applying PCA function on training
# and testing set of X component
from sklearn.decomposition import PCA
  
pca = PCA(n_components = 2)
X = [[0,1],[0,-1]]
X_train = pca.fit_transform(X)

  
explained_variance = pca.explained_variance_ratio_

# print("PCA1 = ",explained_variance)
print("sample covariance\n", np.cov(X))
w,v = np.linalg.eig(X)
print("Eigen vector = \n",v)
print("Eigen value = ", w)
print
print("Eigen vector corresponding to w1 = \n",v[:,0])
print("Eigen vector corresponding to w2 = \n",v[:,1])

sample covariance
 [[ 0.5 -0.5]
 [-0.5  0.5]]
Eigen vector = 
 [[ 1.         -0.70710678]
 [ 0.          0.70710678]]
Eigen value =  [ 0. -1.]
Eigen vector corresponding to w1 = 
 [1. 0.]
Eigen vector corresponding to w2 = 
 [-0.70710678  0.70710678]


In [22]:
import numpy as np
p= [[1,1],[1,-1]]
x = np.dot(1/np.sqrt(2),p)
print(x)
s = np.dot(np.dot(x,[[2,0],[0,1]]),x)
i =[[1,0],[0,1]]
s2 = [[-1,0],[0,-1]]
print(s)
np.matmul(np.matmul(np.transpose(s2),s2),i)

[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
[[1.5 0.5]
 [0.5 1.5]]


array([[1, 0],
       [0, 1]])