Excercise 16

In [44]:
import numpy as np
def IdentityMatrix(n):
    imat = []
    for r in range(n):
        row = []
        for c in range(n):
            if r==c:
                row.append(1)
            else:
                row.append(0)
        imat.append(row)
    return imat
    
def DiagonalMatrix(n,l):
    dmat = []
    for r in range(n):
        row = []
        for c in range(n):
            if r==c:
                row.append(l)
            else:
                row.append(0)
        dmat.append(row)
    return dmat

def H_Func(n):
    one = np.ones(n)
    i = IdentityMatrix(n)
    H = np.subtract(i, np.dot(1/n, np.matmul(one, np.transpose(one))))
    return H

def gramMatrix(vectorList):
    V = np.array(vectorList)
    G = V.dot(V.T)
    return G

def eigenValues(vector):
    w,v  = np.linalg.eig(vector)
    return np.round(w,3)

def eigenVector(vector):
    w,v  = np.linalg.eig(vector)
    return np.round(v,3)

To find the direction of the largest variance between two data points x1=[0,1] and x2=[0,-1], we need to calculate their covariance matrix first.

The covariance matrix of two data points can be calculated as follows:

Covariance matrix = [ cov(x1,x1)  cov(x1,x2) ]

                    [ cov(x2,x1)  cov(x2,x2) ]

where cov(x1,x2) represents the covariance between the two variables x1 and x2.

For our data points x1=[0,1] and x2=[0,-1], we can see that the means of both variables are zero, so the covariance matrix can be simplified to:

Covariance matrix = [ cov(x1,x1)  cov(x1,x2) ]
                    [ cov(x2,x1)  cov(x2,x2) ]
                  = [ 1  0 ]
                    [ 0  1 ]
The covariance matrix is a diagonal matrix, which means that the variables are uncorrelated. Since there is no covariance between the variables, the direction of the largest variance is simply the direction of the variable with the largest variance, which in this case is the y-axis or the direction of [0,1].


### now compute the first principal component for the same

To compute the first principal component for the data points x1=[0,1] and x2=[0,-1], we need to perform a principal component analysis (PCA) on the data.

First, we can stack the two data points into a 2 x 2 matrix X:

X = [0  1]
    [0 -1]

Next, we need to calculate the covariance matrix of X:


Covariance matrix = [ cov(0,0)  cov(0,1) ]
                    [ cov(1,0)  cov(1,-1) ]

Since the means of both variables are zero, the covariance matrix can be simplified to:


Covariance matrix = [ 0  0 ]
                    [ 0  1 ]

We can then find the eigenvectors and eigenvalues of the covariance matrix. The eigenvalues represent the amount of variance in each direction, and the eigenvectors represent the direction of that variance.

To find the first principal component, we need to find the eigenvector corresponding to the largest eigenvalue. In this case, the largest eigenvalue is 1, and the corresponding eigenvector is [0,1].

Therefore, the first principal component for the data points x1=[0,1] and x2=[0,-1] is the direction of the eigenvector [0,1].




### what is the eigen values of the above covariance matrix

The covariance matrix for the data points x1=[0,1] and x2=[0,-1] that we derived earlier is:

Covariance matrix = [ 0  0 ]
                    [ 0  1 ]

To find the eigenvalues of this matrix, we need to solve the characteristic equation:


det(Covariance matrix - λI) = 0

where λ is the eigenvalue, I is the identity matrix, and det() represents the determinant.

Substituting the covariance matrix, we get:


det([0-λ   0  ]
    [0     1-λ]) = 0

Expanding the determinant, we get:

(0-λ)(1-λ) - (0)(0) = 0

Simplifying, we get:


λ^2 - λ = 0

Factoring out λ, we get:


λ(λ - 1) = 0

So the eigenvalues are λ = 0 and λ = 1.

Therefore, the eigenvalues of the covariance matrix for the data points x1=[0,1] and x2=[0,-1] are 0 and 1, respectively. This means that the variance in the x-direction is zero (since the corresponding eigenvalue is 0), and the variance in the y-direction is 1 (since the corresponding eigenvalue is 1).


### eigenvector for the above covariance matrix

To find the eigenvectors of the covariance matrix for the data points x1=[0,1] and x2=[0,-1], we need to solve for the nullspace of the matrix (Covariance matrix - λI), where λ is the eigenvalue.

For λ = 0, we have:

(Covariance matrix - λI) * v = 0

[0  0 ] * [v1]   [0]
[0  1 ]   [v2] = [0]


This gives us the equation 0*v1 + 0*v2 = 0, which means that v2 can take on any value. Therefore, the eigenvector for λ = 0 is [1, 0] (or any multiple of [1, 0]).

For λ = 1, we have:

(Covariance matrix - λI) * v = 0

[-1  0 ] * [v1]   [0]
[ 0  0 ]   [v2] = [0]

This gives us the equation -v1 = 0, which means that v1 must be zero. Therefore, the eigenvector for λ = 1 is [0, 1] (or any multiple of [0, 1]).

So the two eigenvectors for the covariance matrix are [1, 0] and [0, 1], corresponding to the eigenvalues 0 and 1, respectively. Note that these are also the basis vectors for the x- and y-axes, respectively, indicating that the covariance matrix is diagonal and the variables are uncorrelated.


In [2]:
import numpy as np

p12 = 1/(2+np.sqrt(2))
p13 = p12
p23 = np.sqrt(2)/(2+np.sqrt(2))
p12,p23

(0.2928932188134525, 0.4142135623730951)

In [ ]:
x1=[0,1] 
x2=[0,-1]
Covariance_matrix = [[ np.cov(x1,x1),  np.cov(x1,x2) ],
                    [ np.ov(x2,x1),  np.cov(x2,x2) ]]



Calculate the gram matrix of the data points [1,1] [1,-1] [-1,1]

G = [
    [x1 . x1, x1 . x2, x1 . x3],
    [x2 . x1, x2 . x2, x2 . x3],
    [x3 . x1, x3 . x2, x3 . x3]
    ]  

In [45]:
import numpy as np
x1 = [1,1]
x2 = [1,-1]
x3 = [-1,1]

x1t = np.dot(x1, np.transpose(x1))
x2t = np.dot(x2, np.transpose(x2))
x3t = np.dot(x3, np.transpose(x3))
H =H_Func(2)
print(H)
gm = gramMatrix([x1,x2,x3])
print("gramMatrix = \n",gm)

print()
print("eigenValues = ", eigenValues(gm))
print("eigenVectors = ", eigenVector(gm))

[[ 0. -1.]
 [-1.  0.]]
gramMatrix = 
 [[ 2  0  0]
 [ 0  2 -2]
 [ 0 -2  2]]

eigenValues =  [4. 0. 2.]
eigenVectors =  [[ 0.     0.     1.   ]
 [-0.707  0.707  0.   ]
 [ 0.707  0.707  0.   ]]


to perform spectral decomposition on the given Gram matrix G, we need to find its eigenvalues and eigenvectors.

The eigenvalues of G are the solutions to the equation det(G - λI) = 0, where I is the identity matrix and det denotes the determinant.

Substituting G, we get:

det([
    [2 - λ, 0, 0],
    [0, 2 - λ, 0],
    [0, 0, 2 - λ]
    ]) = 0

Expand the determinant,we get:

(2 - λ) * (2 - λ) * (2 - λ) = 0

Solving for λ, we get three eigenvalues: λ1 = 2, λ2 = 2, and λ3 = 2.

To find the eigenvectors of G, we need to solve the equation Gv = λv, where v is a non-zero vector.

For λ1 = 2, we have:

[    [2 - λ1, 0, 0],
    [0, 2 - λ1, 0],
    [0, 0, 2 - λ1]
] * [v1, v2, v3] = [0, 0, 0]



Substituting λ1 and solving, we get:

[    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
] * [v1, v2, v3] = [0, 0, 0]

Since all the rows are zero, we can choose any non-zero value for v1, v2, and v3. For example, we can choose v1 = 1 and v2 = 0, and v3 = 0. Therefore, one eigenvector corresponding to λ1 = 2 is [1, 0, 0].

For λ2 = 2, we have:


[    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
] * [v1, v2, v3] = [0, 0, 0]

Similarly, we can choose any non-zero value for v1, v2, and v3. For example, we can choose v1 = 0 and v2 = 1, and v3 = 0. Therefore, one eigenvector corresponding to λ2 = 2 is [0, 1, 0].

For λ3 = 2, we have:


[    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
] * [v1, v2, v3] = [0, 0, 0]

Again, we can choose any non-zero value for v1, v2, and v3. For example, we can choose v1 = 0 and v2 = 0, and v3 = 1. Therefore, one eigenvector corresponding to λ3 = 2 is [0, 0, 1].

Therefore, the spectral decomposition of the Gram matrix G is:


G = λ1 * v1 *





In [42]:
diag_mat = DiagonalMatrix(3,4)
V = eigenVector(gm)
np.var([[0,1],[0,-1]])


0.5

In [37]:
H_Func(2)

array([[ 0., -1.],
       [-1.,  0.]])